<a href="https://colab.research.google.com/github/chetan6780/ML-Training/blob/master/Assignments/DS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Q.1 Import the numpy package under the name np and Print the numpy version and the configuration


In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


### Q.2 Create a null vector of size 10


In [2]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Q.3 Create Simple 1-D array and check type and check data types in array.


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print("Datatype:", arr.dtype)

Datatype: int64



### Q.4 How to find number of dimensions, bytes per element and bytes of memory used? To find the number of dimensions we use numpy.ndim , To find the bytes per element we use numpy.itemsize and we use numpy.nbytes to find memory used .


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print("Dimensions:", arr.ndim)
print("Bytes per element:", arr.itemsize)
print("Memory used:", arr.nbytes)

Dimensions: 1
Bytes per element: 8
Memory used: 80


### 5 Create a null vector of size 10 but the fifth value which is 1


In [5]:
vector = (np.arange(10) == 4)
vector = vector *1
print(vector)

[0 0 0 0 1 0 0 0 0 0]


### Q.6 Create a vector with values ranging from 10 to 49


In [6]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Q.7 Reverse a vector (first element becomes last)


In [7]:
array = np.array([1, 2, 3, 4, 5, 6])
print("Original vector:", array)
print("Reverse vector:", array[::-1])

Original vector: [1 2 3 4 5 6]
Reverse vector: [6 5 4 3 2 1]


### Q.8 Create a 3x3 matrix with values ranging from 0 to 8




In [8]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Q.9 Find indices of non-zero elements from [1,2,0,0,4,0]


In [9]:
arr = np.array([1,2,0,0,4,0])
print("Index of non zero elements:",*np.nonzero(arr))

Index of non zero elements: [0 1 4]


### Q.10 Create a 3x3 identity matrix


In [10]:
eye_mat = np.eye(3, 3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Q.11 Create a 3x3x3 array with random values.


In [11]:
mat = np.random.random((3, 3, 3))
print(mat)

[[[0.42672605 0.00650611 0.10746686]
  [0.68930513 0.14200698 0.80322591]
  [0.29175974 0.87181559 0.81629441]]

 [[0.14176624 0.139376   0.11085023]
  [0.47981311 0.57276411 0.70211725]
  [0.01026623 0.43557813 0.57649832]]

 [[0.22536622 0.47903466 0.51140107]
  [0.88130402 0.40364459 0.17165186]
  [0.75881656 0.66955843 0.55882158]]]


### Q.12 Create a 10x10 array with random values and find the minimum and maximum values


In [12]:
arr = np.random.random((10, 10))
print(arr)
print("\nMinimum element is:", arr.min())
print("Maximum element is:", arr.max())

[[0.2910428  0.3948103  0.23456613 0.24318428 0.3776848  0.62319487
  0.12070475 0.3060989  0.98789125 0.04517806]
 [0.90723269 0.67213835 0.56669012 0.02226633 0.58913566 0.61403401
  0.92222023 0.87219552 0.27362958 0.24924595]
 [0.29952106 0.56054763 0.12986382 0.96676286 0.13659514 0.11520335
  0.95205    0.60215945 0.6456325  0.36348348]
 [0.62530085 0.48572931 0.40210348 0.79617375 0.22376876 0.9875672
  0.81319376 0.32698368 0.51131978 0.11140488]
 [0.94706128 0.47673567 0.53741485 0.34832888 0.93999727 0.40502771
  0.33929018 0.53190457 0.70955176 0.16357979]
 [0.07948308 0.81868518 0.78487563 0.01106093 0.35398887 0.50388899
  0.87239062 0.16862741 0.71480707 0.03133308]
 [0.33318645 0.78944065 0.39507834 0.72990637 0.92509732 0.44588877
  0.16813903 0.96423261 0.5665126  0.65304152]
 [0.16007262 0.51323771 0.63955402 0.09469104 0.56763544 0.23013835
  0.4252664  0.76615433 0.26082007 0.27324772]
 [0.63387535 0.41844988 0.10329843 0.76496675 0.78280137 0.41912907
  0.63325454 

### Q.13 Create a random vector of size 30 and find the mean value.


In [13]:
vac = np.random.random((10))
print(vac)
print("Mean value of the vector is:", vac.mean())

[0.81102924 0.10285744 0.33993848 0.90522719 0.3953494  0.41704542
 0.89198266 0.02055135 0.27504363 0.82515446]
Mean value of the vector is: 0.49841792767974624


## Q.14 Create a 2d array with 1 on the border and 0 inside.


In [14]:
arr = np.ones((6, 6))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


### Q.15 How to add a border (filled with 0's) around an existing array?
As demonstrated in previous question it is possible with slicing, we just need get the values at border and set them to zero thats it.
```
arr[1:-1, 1:-1] = 0
```

### Q.16 How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?


Example - [[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]
Get 13,get first row only , get 3rd column only, get [2, 4, 6], replace 13 by 20


In [15]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(arr)
print("\nGet 13:\n", arr[1][5])
print("\nFirst row only:\n", arr[0])
print("\n3rd column only:\n", arr[:, 3:4])
print("\nGet [2, 4, 6]:\n", arr[:1, 1:6:2])
print("\nReplace 13 by 20:")
arr[1][5] = 20
print(arr)




[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

Get 13:
 13

First row only:
 [1 2 3 4 5 6 7]

3rd column only:
 [[ 4]
 [11]]

Get [2, 4, 6]:
 [[2 4 6]]

Replace 13 by 20:
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


### Q.17  How to Convert a 1D array to a 2D array with 2 rows.


In [16]:
arr = np.ones((10))
arr = np.reshape(arr,(2,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### 18  Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
    Input:
    a = np.array([1,2,3])

    Desired Output:
    #>> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [17]:
a = np.array([1, 2, 3])
a = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(a)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### Q.19  Write a program to show how Numpy taking less memory compared to Python List?



In [18]:
import numpy as np
import sys

li = range(1000)
print("Size of each element of list in bytes: ", sys.getsizeof(li))
print("Size of the whole list in bytes: ", sys.getsizeof(li)*len(li))

arr = np.arange(1000)
print("Size of each element of the Numpy array in bytes: ", arr.itemsize)
print("Size of the whole Numpy array in bytes: ", arr.size*arr.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


### Q.20  Write a program to show how Numpy taking less time compared to Python List?


In [19]:
import time

size = 1000000

list1 = range(size)
list2 = range(size)
array1 = np.arange(size)
array2 = np.arange(size)

start = time.time()
resList = [(a * b) for a, b in zip(list1, list2)]
print("Multiplication time for list:",(time.time() - start), "seconds.")

start = time.time()
resultantArray = array1 * array2
print("Multiplication time for NumPy array:",(time.time() - start),"seconds.")


Multiplication time for list: 0.12893033027648926 seconds.
Multiplication time for NumPy array: 0.0028934478759765625 seconds.


-----------
